---
title: "Kat.-Nr. 6 BBS 87/1"
output: html_notebook
---

```{r}
library(ca)
library(ggplot2)
library(RColorBrewer)
library(reshape)
library(reshape2)
library(plyr)
library(RSQLite)
library(sqldf)
library(viridis)

drv <- dbDriver("SQLite")
con <- dbConnect(drv, "../data/CongoDB.sqlite")
```

```{r}
df = dbGetQuery(con, "SELECT
           t_Obj.ort_kurz, 
           t_Obj.Komplex, 
           t_Obj.Individuum, 
           t_Obj.Typ, 
           t_Obj.Anzahl,
           t_Obj.Gewicht,
           t_Obj.Gr_Clist, 
           t_Obj.Fabric,
           t_Obj.Art,
           t_Obj.Tiefe 
       FROM (t_Ort INNER JOIN t_Komplex ON t_Ort.ortID = t_Komplex.ortID)
           INNER JOIN t_Obj ON t_Komplex.komplexID = t_Obj.komplexID
       WHERE (((t_Ort.ort_kurz) = 'BBS')
           AND ((t_Komplex.bef_nr) = '87/1'))")
df$Tiefe <- as.numeric(sub(",", ".", df$Tiefe, fixed = TRUE))
head(df)
```

## Art

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Art, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum))
df_pivot
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
# df_melt$value <- df_melt$value / 1000
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)
df_melt
```

```{r}
cols <- read.csv("../data/colPalette/ArtCol.csv")

types <- as.data.frame(unique(df_melt$variable))
colnames(types) <- c("Typ")

types <- merge(x = types, y = cols, by.x = "Typ", by.y = "Art")

types
```

```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), value, fill = factor(variable))) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.5) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm u. NP]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 700)) +
    scale_fill_manual(values = paste(types$col), 
                      label = types$Label, 
                      name = "Material") +  
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          #panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_blank())
          #panel.grid.minor.x = element_blank())
ggsave("../output/figs/9-6_BBS87-1_VerteilungFunde_R.pdf", width = 10, height = 4.3)
```

## Fabrics

```{r}
df$Fabric <- substr(df$Fabric, 0, 2)
df$Fabric <- gsub("[^0-9]", "", df$Fabric)

df_pivot <- data.frame(dcast(df, Tiefe ~ Fabric, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum, 
                             subset = .(!is.na(Fabric))))
# Dummy 8. & 9.-Spalte mit 0 gefüllt erzeugen
df_pivot$X3 <- rep(0,nrow(df_pivot))
df_pivot$X4 <- rep(0,nrow(df_pivot))
df_pivot$X5 <- rep(0,nrow(df_pivot))
df_pivot$X6 <- rep(0,nrow(df_pivot))
df_pivot$X7 <- rep(0,nrow(df_pivot))

df_pivot <- df_pivot[, order(names(df_pivot))]

head(df_pivot)
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
head(df_melt)
```

```{r}
cols <- read.csv("../data/colPalette/FabricCol.csv")
```

```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), value, fill = factor(variable))) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.5) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm u. NP]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 520)) +
    scale_fill_manual(values = paste("#", cols$col, sep = ''), 
                      name = "Fabrics", 
                      label = c(1, 2, 3, 4, 5, 6, 7, 8, 9)) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          panel.grid.major.y = element_blank())
ggsave("../output/figs/9-6_BBS87-1_Fabrics_R.pdf", width = 10, height = 4.3)
```

## Stilgruppe/Typ

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Typ, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum, 
                             subset = .(!is.na(Typ))))
head(df_pivot)
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)

df_melt$rel <- FALSE
df_melt$rel[nchar(as.character(df_melt$variable)) <= 3] <- TRUE

head(df_melt)
```

```{r}
cols <- read.csv("../lit/Wotzka1995_StilGrKuerzel.csv")
cols <- cols[,c("Farbe", "Typ")]

types <- as.data.frame(unique(df_melt$variable))
colnames(types) <- c("Typ")

types$TypEinfach <- substr(types$Typ, 1, 3)
types <- merge(x = types, y = cols, by.x = "TypEinfach", by.y = "Typ")

types
```

```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), 
                    value, 
                    fill = factor(variable),
                    alpha = rel)) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.5) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm u. NP]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 460)) +
    #scale_fill_brewer(palette="Set1") + 
    scale_fill_manual(values = paste("#", types$Farbe, sep = ''),
                      name = "Stilgruppe") +
    scale_alpha_discrete(range = c(0.5, 1), guide=FALSE) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          panel.grid.major.y = element_blank())
ggsave("../output/figs/9-6_BBS87-1_KeramikStilgruppen_R.pdf", width = 10, height = 4.3)
```


## Verteilung der Funde

### Fundkategorien

```{r}
drv <- dbDriver("SQLite")
con <- dbConnect(drv, "../data/CongoDB.sqlite")
df = dbGetQuery(con, "SELECT t_Obj.ort_kurz, t_Obj.Komplex, t_Obj.Individuum, t_Obj.Typ, t_Obj.Gewicht, t_Obj.Gr_Clist, t_Obj.Art, t_Obj.Tiefe FROM t_Obj WHERE (((t_Obj.ort_kurz) = 'BBS') AND ((t_Obj.Komplex) = '87/1'))")
head(df)
```

Kreuztabelle aus der Liste erzeugen:
```{r}
df_pivot <- tapply(df$Gewicht, list(df$Tiefe, df$Art), sum)
df_pivot <- data.frame(df_pivot)
head(df_pivot)
```

Die Matrix muss in eine Liste umgewandelt werden:
```{r}
df_list <- melt(cbind(df_pivot,ind = rownames(df_pivot)),is.vars = c('ind'))
head(df_list)
```

```{r fig.align='center'}
ggplot(df_list, aes(x = ind, y = value)) + geom_bar(aes(fill = variable), colour = "black", stat = "identity", width = 0.5) + coord_flip() + scale_fill_grey(start = 0.3, end = 1) + xlim("40","30", "10" , "0") + xlab("Tiefe [cm]") + ylab("Gewicht [g]") + ggtitle("BBS 87/1\nFundverteilung\n")
# ggsave("../output/figs/9-06_BBS87-1_VerteilungFunde_R.pdf", width = 11, height = 8.5)
```


## Fragmentierung

Daten von der DB abfragen:
```{r}
drv <- dbDriver("SQLite")
con <- dbConnect(drv, "../data/CongoDB.sqlite")
df = dbGetQuery(con, "SELECT t_Obj.ort_kurz, t_Obj.Komplex, t_Obj.Individuum, t_Obj.Gr_Clist, t_Obj.Art FROM t_Obj WHERE (((t_Obj.ort_kurz) = 'BBS') AND ((t_Obj.Komplex) = '87/1') AND ((t_Obj.Art) = 'K'))")
head(df)
```

Kreuztabelle aus der Liste erzeugen:
```{r}
df_pivot <- tapply(df$ort_kurz, list(df$Gr_Clist, df$ort_kurz), length)
df_pivot <- data.frame(df_pivot)
head(df_pivot)
```

da in BBS 87/1 keine Keramik größer als 70 gefunden wurde, muss der Rest manuell eingefügt werden:
```{r}
newRow <- data.frame(BBS=0)
rownames(newRow) <- 120
df_pivot <- rbind(df_pivot, newRow)

newRow <- data.frame(BBS=0)
rownames(newRow) <- 200
df_pivot <- rbind(df_pivot, newRow)

newRow <- data.frame(BBS=0)
rownames(newRow) <- '>200'
df_pivot <- rbind(df_pivot, newRow)

df_pivot

# Zeilenname in neue Spalte kopieren
df_pivot$GrKl <- rownames(df_pivot)

# Sortierung der GrKl soll bestehen bleiben:
df_pivot$GrKl <- as.character(df_pivot$GrKl)
df_pivot$GrKl <- factor(df_pivot$GrKl, levels = unique(df_pivot$GrKl), ordered = TRUE)

df_pivot
```

```{r fig.align='center'}
ggplot(df_pivot, aes(y = BBS)) + geom_bar(aes(x = GrKl), stat = "identity", colour = "black", fill = "white", width = 0.5) + xlab("Größenklassen") + ylab("Anzahl") + ggtitle("BBS 87/1\nFragmentierungsgrad\n")
# ggsave("../output/9-06_BB87-1_KeramikFragmentierung_R.pdf", width = 11, height = 8.5)
```


