---
title: "Kat.-Nr. 8 PIK 87/1"
output: html_notebook
---

# PIK 87/1

```{r}
library(ca)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(plyr)
library(RSQLite)
library(sqldf)
library(viridis)

drv <- dbDriver("SQLite")
con <- dbConnect(drv, "../data/CongoDB.sqlite")
```

## Fachdaten

```{r}
df = dbGetQuery(con, "SELECT
           t_Obj.ort_kurz, 
           t_Obj.Komplex, 
           t_Obj.Individuum, 
           t_Obj.Typ, 
           t_Obj.Schlacke_Typ, 
           t_Obj.Anzahl,
           t_Obj.Gewicht,
           t_Obj.Gr_Clist, 
           t_Obj.Fabric,
           t_Obj.Art,
           t_Obj.Tiefe,
           t_Obj.Notiz
       FROM t_Obj 
       WHERE (((t_Obj.ort_kurz) = 'PIK')
           AND ((t_Obj.Komplex) = '87/1')
           AND ((t_Obj.Notiz) NOT LIKE '%1987%'))")

df$Tiefe <- as.numeric(df$Tiefe)

# alles hinter der zweiten Stelle weg
df$Fabric <- substr(df$Fabric, 0, 2)
# nur grober Typ (alle Buchstaben raus):
df$Fabric <- gsub("[^0-9]", "", df$Fabric)

# Datensätze ohne Tiefenangabe raus
df <- df[!(is.na(df$Tiefe)),]

df
```

## Art

```{r}
# 1987 ausgesonderte Stücke herausnehmen (kommen gleich extra)

df <- sqldf('SELECT * FROM df WHERE Notiz NOT LIKE "%1987%"')
```

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Art, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum))
head(df_pivot)
```



```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)
df_melt$stat <- TRUE
head(df_melt)
```

1987 ausgesonderte Keramik:
```{r}
ausgesond87 = dbGetQuery(con, "SELECT
           t_Obj.Gewicht,
           t_Obj.Art,
           t_Obj.Tiefe 
       FROM t_Obj 
       WHERE (((t_Obj.ort_kurz) = 'PIK')
           AND ((t_Obj.Komplex) = '87/1')
           AND ((t_Obj.Notiz) LIKE '%1987%'))")

ausgesond87 <- data.frame(dcast(ausgesond87, Tiefe ~ Art, 
                                value.var = "Gewicht", 
                                fun.aggregate = sum))

ausgesond87$Tiefe <- as.numeric(ausgesond87$Tiefe)
ausgesond87 <- ausgesond87[order(ausgesond87$Tiefe), ]

colnames(ausgesond87) <- c("Tiefe", "value")
  
ausgesond87$variable <- 'K87'

ausgesond87 <- ausgesond87[,c(1,3,2)]
ausgesond87$stat <- FALSE
ausgesond87
```

```{r}
df_melt2 <- rbind(df_melt, ausgesond87)
df_melt2 <- df_melt2[order(df_melt2$Tiefe, as.character(df_melt2$variable)), ]
#df_melt2 <- df_melt
```

```{r}
cols <- read.csv("../data/colPalette/ArtCol.csv")

types <- as.data.frame(unique(df_melt$variable))
colnames(types) <- c("Typ")

types <- merge(x = types, y = cols, by.x = "Typ", by.y = "Art")

Typ = c("K87") 
col = c("brown1") 
Label = c("Keramik (1987 ausgesondert)") 
a = data.frame(Typ, col, Label) 

types <- rbind(types, a)

#types <- types[order(as.character(types$Label)), ]

types
```


```{r}
ggplot(df_melt2, aes(rev(factor(Tiefe)), 
                    value, 
                    fill = factor(variable),
                    alpha = stat)) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.75) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 8500)) +
    scale_fill_manual(values = paste(types$col),
                      label = types$Label, 
                      name = "Material") + 
    scale_alpha_discrete(range = c(0.5, 1), guide=FALSE) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          #panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_blank()) + 
          #panel.grid.minor.x = element_blank())
    guides(fill=guide_legend(ncol=2))
ggsave("../output/figs/9-8_PIK87-1_VerteilungFunde_R.pdf", width = 10, height = 3)
```


## Fabrics

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Fabric, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum))
# rownames(df_pivot) <- df_pivot$Tiefe
df_pivot <- df_pivot[c("Tiefe", "X1", "X2", "X3", "X4", "X5", "X6", "X7")]
# Dummy 8. & 9.-Spalte mit 0 gefüllt erzeugen
df_pivot$X8 <- rep(0,nrow(df_pivot))
df_pivot$X9 <- rep(0,nrow(df_pivot))
head(df_pivot)
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
# df_melt$value <- df_melt$value / 1000
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)
head(df_melt)
```

```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), value, fill = factor(variable))) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.75) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 2700)) +
    scale_fill_manual(values = c("#e41a1c", "#FF7F00", "#4DAF4A", "#377EB8", "#984EA3", "#999999", "#A65628", "#F781BF", "#FFFF33"), 
                      name = "Fabrics", 
                      label = c(1, 2, 3, 4, 5, 6, 7, 8, 9)) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          panel.grid.major.y = element_blank()) + 
    guides(fill=guide_legend(ncol=2))
ggsave("../output/figs/9-8_PIK87-1_Fabrics_R.pdf", width = 10, height = 3)
```

## Stilgruppe/Typ

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Typ, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum, 
                             subset = .(!is.na(Typ))))
head(df_pivot)
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
# df_melt$value <- df_melt$value / 1000
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)

df_melt$rel <- FALSE
df_melt$rel[nchar(as.character(df_melt$variable)) <= 3] <- TRUE

head(df_melt)
```

```{r}
cols <- read.csv("../lit/Wotzka1995_StilGrKuerzel.csv")
cols <- cols[,c("Farbe", "Typ")]

types <- as.data.frame(unique(df_melt$variable))
colnames(types) <- c("Typ")

types$TypEinfach <- substr(types$Typ, 1, 3)
types <- merge(x = types, y = cols, by.x = "TypEinfach", by.y = "Typ")

types
```

```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), 
                    value, 
                    fill = factor(variable),
                    alpha = rel)) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.75) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 2700)) +
    #scale_fill_brewer(palette="Set1") + 
    scale_fill_manual(values = paste("#", types$Farbe, sep = ''),
                      name = "Stilgruppe") +
    scale_alpha_discrete(range = c(0.5, 1), guide=FALSE) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          panel.grid.major.y = element_blank()) + 
    guides(fill=guide_legend(ncol=2))
ggsave("../output/figs/9-8_PIK87-1_KeramikStilgruppen_R.pdf", width = 10, height = 3)
```

## Schlacken

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Schlacke_Typ, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum))
df_pivot <- df_pivot[c("Tiefe", "X1a", "X2a", "X2c", "X3", "X4a","X5", "X6")]
df_pivot
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)
df_melt
```

```{r}
cols <- read.csv("../data/colPalette/SchlackeCol.csv")

types <- as.data.frame(unique(df_melt$variable))
colnames(types) <- c("Typ")

types <- merge(x = types, y = cols, by.x = "Typ", by.y = "Schlacke_Typ")

types
```


```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), 
                    value, 
                    fill = factor(variable))) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = .75) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 1600)) +
    scale_fill_manual(values = paste(types$col),
                      label = types$Label, 
                      name = "Typ") + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          #panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_blank())
          #panel.grid.minor.x = element_blank())
ggsave("../output/figs/9-8_PIK87-1_Schlacken_R.pdf", width = 10, height = 3)
```





# Seriation Stilgruppen



```{r}
df <- read.csv("../data/processed/9-08_PIK87-1_SeriationList_transf.csv")
df <- sqldf('select * from df where X0 != 0')

# df$Tiefe <- as.character(df$Tiefe)
# df$Tiefe <- factor(df$Tiefe, levels = unique(df$Tiefe), ordered = TRUE)

t <- c(unique(df$Tiefe))

#t <- c(0, 32, 52, 72, 92, 112, 132, 152, 172, 192, 212, 232, 252, 272, 292, 334)

df
```

```{r}
ggplot(df, aes(y = X0)) + 
  geom_bar(aes(x = Tiefe), stat = "identity", colour = "black", fill = "grey") + 
  facet_grid(. ~ Typ1) + 
  coord_flip() + 
  theme_bw() + 
  scale_x_reverse(breaks = t) +  
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
ggsave("../output/figs/9-8_PIK87-1_VerteilungFunde_Seriation.pdf", width = 12, height = 6)
```






