---
title: "Kat.-Nr. 9 PIK 87/2"
output: html_notebook
---

# PIK 87/1

```{r}
library(ca)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(plyr)
library(RSQLite)
library(sqldf)
library(viridis)

drv <- dbDriver("SQLite")
con <- dbConnect(drv, "../data/CongoDB.sqlite")
```

## Fachdaten

```{r}
df = dbGetQuery(con, "SELECT
           t_Obj.ort_kurz, 
           t_Obj.Komplex, 
           t_Obj.Individuum, 
           t_Obj.Typ, 
           t_Obj.Anzahl,
           t_Obj.Gewicht,
           t_Obj.Gr_Clist, 
           t_Obj.Fabric,
           t_Obj.Art,
           t_Obj.Tiefe,
           t_Obj.Notiz
       FROM t_Obj 
       WHERE (((t_Obj.ort_kurz) = 'PIK')
           AND ((t_Obj.Komplex) = '87/2'))")

df$Tiefe <- as.numeric(df$Tiefe)

# alles hinter der zweiten Stelle weg
df$Fabric <- substr(df$Fabric, 0, 2)
# nur grober Typ (alle Buchstaben raus):
df$Fabric <- gsub("[^0-9]", "", df$Fabric)

# Datensätze ohne Tiefenangabe raus
df <- df[!(is.na(df$Tiefe)),]

df
```

```{r}
with(df, tapply(Gewicht, list(Art), sum))
```

```{r}
sum(df$Gewicht)
```


## Art

```{r}
# 1987 ausgesonderte Stücke herausnehmen (kommen gleich extra)

df <- sqldf('SELECT * FROM df WHERE Notiz NOT LIKE "%1987%"')
```


```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Art, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum))
head(df_pivot)
```



```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)
df_melt$stat <- TRUE
head(df_melt)
```

1987 ausgesonderte Keramik:
```{r}
ausgesondK87 = dbGetQuery(con, "SELECT
           t_Obj.Gewicht,
           t_Obj.Art,
           t_Obj.Tiefe 
       FROM t_Obj 
       WHERE (((t_Obj.ort_kurz) = 'PIK')
           AND ((t_Obj.Komplex) = '87/2')
           AND ((t_Obj.Notiz) LIKE '%1987%')
           AND ((t_Obj.Art) = 'K'))")

ausgesondK87 <- data.frame(dcast(ausgesondK87, Tiefe ~ Art, 
                                value.var = "Gewicht", 
                                fun.aggregate = sum))

ausgesondK87$Tiefe <- as.numeric(ausgesondK87$Tiefe)
ausgesondK87 <- ausgesondK87[order(ausgesondK87$Tiefe), ]

colnames(ausgesondK87) <- c("Tiefe", "value")
  
ausgesondK87$variable <- 'K87'

ausgesondK87 <- ausgesondK87[,c(1,3,2)]
ausgesondK87$stat <- FALSE
ausgesondK87
```

```{r}
sum(ausgesondK87$value)
```

1987 ausgesonderte Schlacken:
```{r}
ausgesondS87 = dbGetQuery(con, "SELECT
           t_Obj.Gewicht,
           t_Obj.Art,
           t_Obj.Tiefe 
       FROM t_Obj 
       WHERE (((t_Obj.ort_kurz) = 'PIK')
           AND ((t_Obj.Komplex) = '87/2')
           AND ((t_Obj.Notiz) LIKE '%1987%')
           AND ((t_Obj.Art) LIKE '%Schlacke%'))")

ausgesondS87 <- data.frame(dcast(ausgesondS87, Tiefe ~ Art, 
                                value.var = "Gewicht", 
                                fun.aggregate = sum))

ausgesondS87$Tiefe <- as.numeric(ausgesondS87$Tiefe)
ausgesondS87 <- ausgesondS87[order(ausgesondS87$Tiefe), ]

colnames(ausgesondS87) <- c("Tiefe", "value")
  
ausgesondS87$variable <- 'S87'

ausgesondS87 <- ausgesondS87[,c(1,3,2)]
ausgesondS87$stat <- FALSE
ausgesondS87
```

```{r}
sum(ausgesondS87$value)
```


```{r}
df_melt2 <- rbind(df_melt, ausgesondK87, ausgesondS87)
df_melt2 <- df_melt2[order(df_melt2$Tiefe, as.character(df_melt2$variable)), ]
#df_melt2 <- df_melt
```

```{r}
cols <- read.csv("../data/colPalette/ArtCol.csv")

types <- as.data.frame(unique(df_melt$variable))
colnames(types) <- c("Typ")

types <- merge(x = types, y = cols, by.x = "Typ", by.y = "Art")

Typ = c("K87") 
col = c("brown1") 
Label = c("Keramik (1987 ausgesondert)") 
a = data.frame(Typ, col, Label) 

types <- rbind(types, a)

Typ = c("S87") 
col = c("violet") 
Label = c("Schlacke (1987 ausgesondert)") 
a = data.frame(Typ, col, Label) 

types <- rbind(types, a)

#types <- types[order(as.character(types$Label)), ]

types
```

```{r}
ggplot(df_melt2, aes(rev(factor(Tiefe)), 
                    value, 
                    fill = factor(variable),
                    alpha = stat)) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.5) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 26000)) +
    scale_fill_manual(values = paste(types$col),
                      label = types$Label, 
                      name = "Material") + 
    scale_alpha_discrete(range = c(0.5, 1), guide=FALSE) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          #panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_blank())
          #panel.grid.minor.x = element_blank())
ggsave("../output/figs/9-9_PIK87-2_VerteilungFunde_R.pdf", width = 10, height = 4.3)
```


## Fabrics

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Fabric, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum))
# rownames(df_pivot) <- df_pivot$Tiefe
df_pivot <- df_pivot[c("Tiefe", "X1", "X2", "X3", "X4", "X5", "X6", "X7")]
# Dummy 8. & 9.-Spalte mit 0 gefüllt erzeugen
df_pivot$X8 <- rep(0,nrow(df_pivot))
df_pivot$X9 <- rep(0,nrow(df_pivot))
head(df_pivot)
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
# df_melt$value <- df_melt$value / 1000
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)
head(df_melt)
```

```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), value, fill = factor(variable))) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.5) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 950)) +
    scale_fill_manual(values = c("#e41a1c", "#FF7F00", "#4DAF4A", "#377EB8", "#984EA3", "#999999", "#A65628", "#F781BF", "#FFFF33"), 
                      name = "Fabrics", 
                      label = c(1, 2, 3, 4, 5, 6, 7, 8, 9)) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          panel.grid.major.y = element_blank())
ggsave("../output/figs/9-9_PIK87-2_Fabrics_R.pdf", width = 10, height = 4.3)
```

## Stilgruppe/Typ

```{r}
df_pivot <- data.frame(dcast(df, Tiefe ~ Typ, 
                             value.var = "Gewicht", 
                             fun.aggregate = sum, 
                             subset = .(!is.na(Typ))))
head(df_pivot)
```

```{r}
df_melt <- melt(df_pivot, id.vars = "Tiefe")
# df_melt$value <- df_melt$value / 1000
df_melt$Tiefe <- as.numeric(df_melt$Tiefe)

df_melt$rel <- FALSE
df_melt$rel[nchar(as.character(df_melt$variable)) <= 3] <- TRUE

head(df_melt)
```

```{r}
cols <- read.csv("../lit/Wotzka1995_StilGrKuerzel.csv")
cols <- cols[,c("Farbe", "Typ")]

types <- as.data.frame(unique(df_melt$variable))
colnames(types) <- c("Typ")

types$TypEinfach <- substr(types$Typ, 1, 3)
types <- merge(x = types, y = cols, by.x = "TypEinfach", by.y = "Typ")

types
```

```{r}
ggplot(df_melt, aes(rev(factor(Tiefe)), 
                    value, 
                    fill = factor(variable),
                    alpha = rel)) + 
    geom_bar(stat = "identity", color = 'black', size = 0.25, width = 0.5) + 
    coord_flip() + 
    scale_x_discrete("Tiefe [cm]", labels = c(rev(df_melt$Tiefe))) + 
    scale_y_continuous("Gewicht [g]", expand = c(0, 0), limits = c(0, 1800)) +
    #scale_fill_brewer(palette="Set1") + 
    scale_fill_manual(values = paste("#", types$Farbe, sep = ''),
                      name = "Stilgruppe") +
    scale_alpha_discrete(range = c(0.5, 1), guide=FALSE) + 
    theme_bw() + 
    theme(legend.justification = c(1, 0), 
          legend.position = c(.99, .01), 
          panel.grid.major.y = element_blank()) + 
    guides(fill=guide_legend(ncol=2))
ggsave("../output/figs/9-9_PIK87-2_KeramikStilgruppen_R.pdf", width = 10, height = 4.3)
```
