---
title: "Kat.-Nr. 10 PIK 87/3"
output: html_notebook
---

# PIK 87/3

```{r}
library(ca)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(plyr)
library(RSQLite)
library(scales)
library(sqldf)
library(viridis)

source("myfunctions.R")

drv <- dbDriver("SQLite")
con <- dbConnect(drv, "../data/CongoDB.sqlite")
```

## Fachdaten

```{r}
df = dbGetQuery(con, "SELECT
           t_Obj.ort_kurz, 
           t_Obj.Komplex, 
           t_Obj.Individuum, 
           t_Obj.Typ, 
           t_Obj.Anzahl,
           t_Obj.Gewicht,
           t_Obj.Gr_Clist, 
           t_Obj.Fabric,
           t_Obj.Art,
           t_Obj.Schlacke_Typ,
           t_Obj.Notiz
       FROM t_Obj 
       WHERE (((t_Obj.ort_kurz) = 'PIK')
           AND ((t_Obj.Komplex) = '87/3'))")
df
```

```{r}
sum(df$Gewicht)
```

## Art

```{r}
a <- sqldf('SELECT * FROM df WHERE Art != ""')

df_pivot <- as.data.frame(with(df, tapply(Gewicht, list(Art), sum)))

colnames(df_pivot) <- c("value")
df_pivot$group <- rownames(df_pivot)
rownames(df_pivot) <- NULL

df_pivot$pct <- round(df_pivot$value / sum(df_pivot$value) * 100)

df_pivot
```

```{r}
cols <- read.csv("../data/colPalette/ArtCol.csv")

types <- as.data.frame(unique(df_pivot$group))
colnames(types) <- c("Typ")

types <- merge(x = types, y = cols, by.x = "Typ", by.y = "Art")

types
```


```{r}
ggplot(df_pivot, aes(x="", y=value, fill=group)) + 
  geom_bar(width = 1, stat = "identity", color = 'black') + 
  coord_polar("y", start=0) + 
  scale_fill_manual(values = paste(types$col), 
                    label = types$Label,
                    name = "Material") + 
  blank_theme +
  theme(axis.text.x=element_blank()) + 
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
            label = paste(types$Label, "\n(", percent(pct/100), ")", sep = "")), size=5) + 
  theme(legend.position="none")
ggsave("../output/figs/9-10_PIK87-3_Funde_R.pdf", width = 6, height = 6)
```

## Stilgruppe/Typ

```{r}
a <- sqldf('SELECT * FROM df WHERE Typ != ""')

df_pivot <- as.data.frame(with(df, tapply(Gewicht, list(Typ), sum)))

colnames(df_pivot) <- c("value")
df_pivot$group <- rownames(df_pivot)
rownames(df_pivot) <- NULL

df_pivot$pct <- round(df_pivot$value / sum(df_pivot$value) * 100)

df_pivot$rel <- FALSE
df_pivot$rel[nchar(as.character(df_pivot$group)) <= 3] <- TRUE

df_pivot
```

```{r}
cols <- read.csv("../lit/Wotzka1995_StilGrKuerzel.csv")
cols <- cols[,c("Farbe", "Typ")]

types <- as.data.frame(unique(df_pivot$group))
colnames(types) <- c("Typ")

types$TypEinfach <- substr(types$Typ, 1, 3)
types <- merge(x = types, y = cols, by.x = "TypEinfach", by.y = "Typ")

types
```

```{r}
ggplot(df_pivot, aes(x = "", 
                     y = value,
                     fill = group,
                     alpha = rel)) + 
  geom_bar(width = 1, stat = "identity", color = 'black') + 
  coord_polar("y", start=0) + 
  scale_fill_manual(values = paste("#", types$Farbe, sep = '')) +
  scale_alpha_discrete(range = c(0.66, 1), guide=FALSE) + 
  blank_theme +
  theme(axis.text.x=element_blank()) + 
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
            label = paste(group, "\n(", percent(pct/100), ")", sep = "")), alpha = 1, size=5) + 
  theme(legend.position="none")
ggsave("../output/figs/9-10_PIK87-3_Stilgruppen_R.pdf", width = 6, height = 6)
```


## Schlacken-Typen

```{r}
a <- sqldf('SELECT * FROM df WHERE Schlacke_Typ != ""')

df_pivot <- as.data.frame(with(a, tapply(Gewicht, list(Schlacke_Typ), sum)))

colnames(df_pivot) <- c("value")
df_pivot$group <- rownames(df_pivot)
rownames(df_pivot) <- NULL

df_pivot$pct <- round(df_pivot$value / sum(df_pivot$value) * 100)

df_pivot
```

```{r}
ggplot(df_pivot, aes(x="", y=value, fill=group)) + 
  geom_bar(width = 1, stat = "identity", color = 'black') + 
  coord_polar("y", start=0) + 
  blank_theme +
  theme(axis.text.x=element_blank()) + 
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
            label = paste(group, "\n(", percent(pct/100), ")", sep = "")), size=5) + 
  theme(legend.position="none")
ggsave("../output/figs/9-10_PIK87-3_Schlacketypen_R.pdf", width = 6, height = 6)
```

## Fragmentierung

```{r}
df = dbGetQuery(con, "SELECT 
                  t_Obj.objID,
                  t_Obj.Gr_Clist,
                  t_Obj.Anzahl,
                  t_Obj.Gewicht
                FROM (t_Ort INNER JOIN t_Komplex ON t_Ort.ortID = t_Komplex.ortID)
                  INNER JOIN t_Obj ON t_Komplex.komplexID = t_Obj.komplexID 
                WHERE (((t_Obj.ort_kurz) = 'PIK')
                  AND ((t_Obj.Komplex) = '87/3')
                  AND ((t_Obj.Gr_Clist) != '')
                  AND ((t_Obj.Art) = 'K'))")
head(df)

# Dummy-Werte erzeugen

objID = c(0, 0, 0, 0, 0)
Gr_Clist = c(30, 70, 120, 200, 500) 
Anzahl = c(0, 0, 0, 0, 0) 
Gewicht = c(0, 0, 0, 0, 0)
df_dummy = data.frame(objID, Gr_Clist, Anzahl, Gewicht) 
# Dummy-Liste an df anhängen
df <- rbind(df, df_dummy)
  
# Gewicht Summe ausrechnen
df_a <- data.frame(tapply(df$Gewicht, list(df$Gr_Clist), sum))
names(df_a)[1] <- "value"
# Index als Spalte
df_a$variable <- rownames(df_a) 

# Anzahl Summe ausrechnen
df_b <- data.frame(tapply(df$Anzahl, list(df$Gr_Clist), sum))
names(df_b)[1] <- "value"
# Index als Spalte
df_b$variable <- rownames(df_b) 

# Sortierung beibehalten
df_a$variable[df_a$variable == "500"] <- ">200"
df_a$variable <- as.character(df_a$variable)
df_a$variable <- factor(df_a$variable, levels = unique(df_a$variable), ordered = TRUE)

df_b$variable[df_b$variable == "500"] <- ">200"
df_b$variable <- as.character(df_b$variable)
df_b$variable <- factor(df_b$variable, levels = unique(df_b$variable), ordered = TRUE)

# für Limit maximum ermitteln und 5% draufschlagen
max_a <- max(df_a$value, na.rm = TRUE)
max_a <- max_a + (0.05*max_a)
max_b <- max(df_b$value, na.rm = TRUE)
max_b <- max_b + (0.05*max_b)


# Einzelteile des späteren Plots erzeugen
g.mid <- ggplot(df_a,aes(x = 1,y = variable)) + 
  geom_text(aes(label = variable), size = 4) +
  geom_segment(aes(x = 0.94,xend = 0.96,yend = variable))+
  geom_segment(aes(x = 1.04,xend = 1.065,yend = variable))+
  ylab(NULL)+
  scale_x_continuous(name = "", expand=c(0,0),limits=c(0.94,1.065)) + 
  theme(axis.title.y = element_blank(),
        panel.grid = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(color = NA),
        axis.ticks.x = element_line(color = NA),
        plot.margin = unit(c(1,-1,1,1), "mm"))

g1 <- ggplot(df_a, aes(x = variable, y = value)) +
  geom_bar(stat="identity", width = 0.5, fill = "grey", color = "black") + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        plot.margin = unit(c(1,5,1,1), "mm"), 
        axis.ticks.margin = unit(0.35, "cm")) + 
  scale_x_discrete(name = "") + 
  scale_y_continuous(name = "Gewicht [g]", limits = c(0, max_a), expand = c(0,0)) + 
  coord_flip()

g2 <- ggplot(df_b, aes(x = variable, y = value)) +
  geom_bar(stat="identity", width = 0.5, fill = "grey", color = "black") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        plot.margin = unit(c(1,1,1,5), "mm"), 
        axis.ticks.margin = unit(0.35, "cm")) +  
  scale_x_discrete(name = "") + 
  scale_y_reverse(name = "Anzahl", limits = c(max_b, 0), expand = c(0,0)) + 
  coord_flip()

gg1 <- ggplot_gtable(ggplot_build(g1))
gg2 <- ggplot_gtable(ggplot_build(g2))
gg.mid <- ggplot_gtable(ggplot_build(g.mid))

pdf("../output/figs/9-10_PIK87-3_Fragmentierung.pdf", width = 10, height = 2.5)
grid.arrange(gg2, gg.mid, gg1, ncol = 3, widths = c(4/9,1/9,4/9))
dev.off()
```


```{r}
# n in dieser Abb:
sum(df_b$value)
```

